[package]
name = "foto"
version = "0.1.0"
edition = "2021"
description = "A CLI tool for image processing"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
clap-markdown = "0.1.5"
image = "0.24"