[package]
name = "foto"
version = "0.1.0"
edition = "2021"
description = "A CLI tool for image processing"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.24"
anyhow = "1.0"
